### ISSUE TITLE
Please add support for the new Chromium-based Microsoft Edge browser

### ISSUE THREAD

**Issue by alexdresko** [htrinter/Open-Multiple-URLs#12]
I wish this extension was available on the new Chromium-based Edge browser that just came out. 

https://www.microsoft.com/en-us/edge?form=MO12GC&OCID=MO12GC

**Comment by jtagcat** [comment]
Please add support for Linux for the new Chromium-based Microsoft Edge browser.

**Comment by jtagcat** [comment]
Get it from the chrome store.
https://chrome.google.com/webstore/detail/open-multiple-urls/oifijhaokejakekmnjmphonojcfkpbbh
This extension is too small to bother with yet another store to have to publish on, our time is limited as well.

**Comment by alexdresko** [comment]
Will you accept a PR? It's not hard to do the conversion, and I find that installing from the Chrome store is annoying.

**Comment by jtagcat** [comment]
I can agree to accept a PR, since [I'm taking over](https://github.com/htrinter/Open-Multiple-URLs/pull/14). Though I'd need write access to this repository by @htrinter (who has been inactive since november).
Moving the extension on Chrome Web store and AMO would be preferrable as well.

An option would be me forking this, but this would mean that the old users who already use this extension would be abandoned.

**Comment by alexdresko** [comment]
@jtagcat Interesting situation. I suppose if he's not going to accept PRs, it'd be better to just fork it.

**Comment by jtagcat** [comment]
Update: @htrinter has risen from the dead

**Comment by htrinter** [comment]
The extension works with Edge (Chromium) and can be installed via Google's Chrome Web Store. At the moment I do not want to jump through all the hoops required to publish and maintain another store listing.
