### ISSUE TITLE
Using This Add-On Disables Copying/Pasting from Firefox

### ISSUE THREAD

**Issue by brockn8r** [htrinter/Open-Multiple-URLs#47]
For whatever reason - whether it is a Firefox bug, or your add-on - copying and pasting is disabled from/to Firefox after adding this add-on. If I remove, it all works again. 

I am using Firefox 94.0 (64-bit)

I am running on Fedora 33. 

Simple test:
1. Add the multiple URL add-on
2. Open any URL (say www.finance.yahoo.com)
3. Double-click the address bar (so as to select the entire URL)
4. Type cntrl-C (or right-click -> "Copy")
5. Open up any other app to paste. Notice that the buffer is empty and nothing gets pasted.

**Comment by htrinter** [comment]
Hi, I am not able to reproduce the issue with Firefox 95 running on Xubuntu. The addon does not execute in the background, only when the popup is triggered via browseraction. Which is controlled by the browser. So I would assume this is a bug with Firefox, because the addon itself is not able to modify the behaviour described. Does restarting the browser or upgrading to v95 help?

**Comment by brockn8r** [comment]
The only method I have found to fix the problem is to "Refresh Firefox". I do this by clicking on the "hamburger" in the upper right, and selecting Help -> More troubleshooting information, and then clicking on the "Refresh Firefox..." button in the upper right. Unfortunately, that clears out everything (including removing this add-on).

https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

Simply restarting Firefox does not help - nor does rebooting my workstation.

**Comment by brockn8r** [comment]
I just did a manual update to v95, and I found that the problem no longer exists; hence, I am closing this issue out. Thanks for responding.
